spring.application.name=traceback-api


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:3zpQj4pbSkrBCdh.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ychT7RlhnHgCaeqL}

# 2. Hibernate Settings (Safe to keep as is)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud_name=${CLOUDINARY_NAME:dwc9j1cfb}
cloudinary.api_key=${CLOUDINARY_KEY:239558525384221}
cloudinary.api_secret=${CLOUDINARY_SECRET:4jQ3Lysw0p7oLs6DmaedNUXDh1Y}


app.jwt.secret=${JWT_SECRET:TracebackSuperSecretKeyForJwtGenerationMustBeLongEnough!}