spring.application.name=traceback-api


# 1. Database - These will be filled by Koyeb/Railway later
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# 2. Hibernate Settings (Safe to keep as is)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Cloudinary - These will be filled by Koyeb/Railway later
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}


app.jwt.secret=${JWT_SECRET}